/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionesumg;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author wdiaz
 */
public class Encuesta extends javax.swing.JFrame {

    /**
     * Creates new form Encuesta
     */
    public Encuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoLinux = new javax.swing.ButtonGroup();
        GrupoEspecialidad = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        RBWindows = new javax.swing.JRadioButton();
        SBMac = new javax.swing.JRadioButton();
        RBLinux = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        CBProgramacion = new javax.swing.JCheckBox();
        CBDisenografico = new javax.swing.JCheckBox();
        CBAdrministracion = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        ButtonEncuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GrupoLinux.add(RBWindows);
        RBWindows.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        RBWindows.setText("Windows");

        GrupoLinux.add(SBMac);
        SBMac.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        SBMac.setText("Mac");

        GrupoLinux.add(RBLinux);
        RBLinux.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        RBLinux.setText("Linux");

        jLabel2.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        jLabel2.setText("¿Cual es tu especialidad?");

        jLabel3.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        jLabel3.setText("¿Que sistema operativo prefieres?");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        GrupoEspecialidad.add(CBProgramacion);
        CBProgramacion.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        CBProgramacion.setText("Programacion");

        GrupoEspecialidad.add(CBDisenografico);
        CBDisenografico.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        CBDisenografico.setText("Diseño Grafico");

        GrupoEspecialidad.add(CBAdrministracion);
        CBAdrministracion.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        CBAdrministracion.setText("Administracion");

        jLabel4.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        jLabel4.setText("¿Cuantas horas dedicas en el ordenador?");

        ButtonEncuesta.setFont(new java.awt.Font("Charter", 0, 12)); // NOI18N
        ButtonEncuesta.setText("GENERAR");
        ButtonEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEncuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBProgramacion)
                            .addComponent(jLabel2)
                            .addComponent(CBDisenografico)
                            .addComponent(CBAdrministracion)
                            .addComponent(RBWindows)
                            .addComponent(SBMac)
                            .addComponent(RBLinux)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ButtonEncuesta)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBWindows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SBMac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBLinux)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBProgramacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBDisenografico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBAdrministracion)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEncuesta)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEncuestaActionPerformed

        RBWindows.setText("Windows");
        SBMac.setText("Mac");
        RBLinux.setText("Linux");

        CBProgramacion.setText("Programacion");
        CBDisenografico.setText("Diseño");
        CBAdrministracion.setText("Administracion");

        JRadioButton[] radioButtons = {RBWindows, SBMac, SBMac};
        JCheckBox[] checkButtons = {CBProgramacion, CBDisenografico, CBAdrministracion};
        
        String msgso = "";
        String msgsc = "";

        if (RBWindows.isSelected() == false && SBMac.isSelected() == false && RBLinux.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado Sistema Operativo");
        }

        if (CBProgramacion.isSelected() == false && CBDisenografico.isSelected() == false && CBAdrministracion.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado Especialidad");
        }

        for (int sistema = 0; sistema < radioButtons.length; sistema++) {
            if (radioButtons[sistema].isSelected()) {
                msgso = radioButtons[sistema].getText();
            }
        }

        for (int especialidad = 0; especialidad < checkButtons.length; especialidad++) {
            if (checkButtons[especialidad].isSelected()) {
                msgsc = radioButtons[especialidad].getText();
            }
        }

        JOptionPane.showMessageDialog(null, "Tu sistema operativo favorito: " + msgso + "\n Tu especialidad: " + msgsc);

    }//GEN-LAST:event_ButtonEncuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEncuesta;
    private javax.swing.JCheckBox CBAdrministracion;
    private javax.swing.JCheckBox CBDisenografico;
    private javax.swing.JCheckBox CBProgramacion;
    private javax.swing.ButtonGroup GrupoEspecialidad;
    private javax.swing.ButtonGroup GrupoLinux;
    private javax.swing.JRadioButton RBLinux;
    private javax.swing.JRadioButton RBWindows;
    private javax.swing.JRadioButton SBMac;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
